action: watermark
dataset: cifar10
batch_size: 128
arch: resnet18
epochs: 1
lr: 0.001
key_num: 500
key_target: 4
wm_lr: 0.001
wm_epoch: 1
wm_it: 5
clean_model_path: logs/cifar10/clean/mm-dd-hh-mi-runname/last.pt  # replace this with the path to a trained model
